# 漏洞忽略規則配置檔案
# 用於定義哪些漏洞應該被忽略以及忽略的原因

rules:
  # 依 CVE ID 忽略特定漏洞
  - cve: CVE-2023-26136
    reason: "已確認為誤報，實際使用中不會觸發此漏洞"
    expires: "2024-06-30"  # 可選：設定忽略規則的到期日期

  # 依 CVE ID 和套件名稱忽略 (更精確的匹配)
  - cve: CVE-2022-25883
    package: semver
    reason: "此版本在我們的使用情境下不會受到影響，等待下個維護窗口統一更新"
    expires: "2024-03-31"

  # 永久忽略 (不設定 expires)
  - cve: CVE-2023-26115
    reason: "開發依賴套件，不影響生產環境安全"

  # 臨時忽略，用於已知問題但暫時無法修復的情況
  - cve: CVE-2023-45133
    package: "@babel/traverse"
    reason: "正在評估升級影響，預計兩週內完成修復"
    expires: "2024-02-15"