# 通知器配置範例
# 支援多個通知器同時發送通知

notifiers:
  # Microsoft Teams 通知
  - type: teams
    enabled: true
    config:
      webhookUrl: 'https://outlook.office.com/webhook/your-webhook-url-here'

  # 未來可擴展的其他通知器範例：

  # Slack 通知 (未實作，僅示範結構)
  # - type: slack
  #   enabled: false
  #   config:
  #     webhookUrl: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  #     channel: "#security-alerts"

  # Discord 通知 (未實作，僅示範結構)
  # - type: discord
  #   enabled: false
  #   config:
  #     webhookUrl: "https://discord.com/api/webhooks/YOUR/DISCORD/WEBHOOK"

  # 電子郵件通知 (未實作，僅示範結構)
  # - type: email
  #   enabled: false
  #   config:
  #     smtpHost: "smtp.gmail.com"
  #     smtpPort: 587
  #     username: "your-email@example.com"
  #     password: "your-app-password"
  #     to: ["security-team@example.com", "devops@example.com"]
  #     subject: "安全掃描報告"
